const constantDataType = {
  LOGIN: "LOGIN",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGOUT: "LOGOUT",
  ADD_DEVICE: "ADD_DEVICE",
  ADD_SUCCESS: "ADD_SUCCESS",
  ADD_ERROR: "ADD_ERROR",
  FETCH_TYPE_ERROR: "FETCH_TYPE_ERROR",
  FETCH_TYPE_START: "FETCH_TYPE_START",
  FETCH_TYPE_SUCCESS: "FETCH_TYPE_SUCCESS",
  FETCH_MODEL_SUCCESS: "FETCH_MODEL_SUCCESS",
  FETCH_MODEL_ERROR: "FETCH_MODEL_ERROR",
  FETCH_MODEL_START: "FETCH_MODEL_START",
  DEVICE_PAGE_CHANGE: "DEVICE_PAGE_CHANGE",
  DEVICE_LIMIT_CHANGE: "DEVICE_LIMIT_CHANGE",
  PRODUCT_LOAD_SUCCESS: "PRODUCT_LOAD_SUCCESS",
  PRODUCT_LOAD_START: "PRODUCT_LOAD_START",
  PRODUCT_LOAD_ERROR: "PRODUCT_LOAD_ERROR",
}

export default constantDataType
